version: '3.6'

services:
  redis:
    container_name: redis-container
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge