version: '3.7'

networks:
  app:

services:
  backend:
    container_name: admin_api
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_DATABASE: admin
      DB_USERNAME: testing
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - app

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8077:80'
    environment: 
      - PMA_HOST=database
    depends_on:
          - database

  database:
    container_name: admin_db
    image: mysql:latest
    ports:
      - '5506:3306'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: suraj_test_user
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345