version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
  apache:
    image: php:7.4-apache
    volumes:
      - ./public-html:/var/www/html
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - apache
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  db-data:
