version: '3'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - '8077:80'
        environment: 
         - PMA_HOST=database
        depends_on:
          - database

    database:
      image: mysql:latest
      ports:
        - '5506:3306'
      restart: unless-stopped
      environment:
        MYSQL_USER: laravel_user
        MYSQL_PASSWORD: 12345
        MYSQL_ROOT_PASSWORD: 12345